apiVersion: v1
kind: Service
metadata:
  name: space-invaders
  namespace: space-fleet
  labels:
    app: space-invaders
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: space-invaders
